### ISSUE TITLE
Prevent common issues on NuvlaBox Engine and NuvlaBox OS

### ISSUE THREAD

**Issue by schaubl** [nuvlabox/nuvlabox#24]
- [x] Increase Swarm certificate expiry on NuvlaBox OS and document it as a good practice for NuvlaBox Engine. 
nuvlabox/nuvlabox-os#22
- [x] Create a cron job on NuvlaBox OS to renew Swarm certificate more regularly and suggest/document this cron job for NuvlaBox Engine. 
nuvlabox/nuvlabox-os#23
- [x] Ensure system-manager doesn't kill NB Engine containers on NB OS. Document this parameter for NB Engine or maybe set it by default. 
nuvlabox/nuvlabox-os#24
- [x] Allow to define Environment Variables in the auto install context file (required for the point above). 
nuvlabox/nuvlabox#23
- [x] Add the Swarm certificate expiry date to the data sent via the telemetry. 
nuvlabox/agent#60
